[package]
name = "sql-parser"
version = "0.1.0"
authors = ["mdauthentic <muideen.lawal320@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
